version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    depends_on:
      - backend
      - encryptor
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
    - ${REACT_APP_PRODUCTION_PORT}:${REACT_APP_PRODUCTION_PORT}
    tty: true
    network_mode: host
  encryptor:
    build:
      context: .
      dockerfile: encryptor.docker
    volumes:
      - ./encryptor:/var/www/encryptor
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /var/www/api
    volumes:
      - ${NEDB_DIRECTORY}
      - ${LOCAL_FILES_DIRECTORY}
      - ${MEDIA_ATTACHMENTS_DIRECTORY}
    env_file:
      - .env
    ports:
    - ${DATA_VALIDATOR_API_PORT}:${DATA_VALIDATOR_API_PORT}
#    network_mode: host
    networks:
      - default
volumes:
  pg-data: {}
